apiVersion: v1
kind: ConfigMap
metadata:
  name: oncall-prober-config
data:
  MySqlSettings__user: "root"
  MySqlSettings__password: "1234"
  MySqlSettings__host: "oncall-mysql"
  MySqlSettings__port: "3306"
  MySqlSettings__charset: "utf8"
  AppDbDatabase: "oncall"
  SlaDbDatabase: "sla"
  ExporterSettings__ApiUrl: "http://oncall.local"
  ExporterSettings__ScrapeInterval: "30"
  ExporterSettings__MetricsPort: "8000"
  ExporterSettings__AppSettings__Name: "oncall_prober"
  ExporterSettings__AppSettings__Key: "somesupersecretkey"
  PrometheusSettings__ApiUrl: "localhost:9090"
  PrometheusSettings__ScrapeInterval: "60"
