apiVersion: apps/v1
kind: Deployment
metadata:
  name: oncall-prober
  labels:
    app.kubernetes.io/name: oncall-prober
    app.kubernetes.io/component: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: oncall-prober
      app.kubernetes.io/component: web
  template:
    metadata:
      labels:
        app.kubernetes.io/name: oncall-prober
        app.kubernetes.io/component: web
    spec:
      hostAliases:
      - ip: "192.168.49.1"
        hostnames:
        - "host.minikube.internal"
      containers:
      - name: oncall-prober
        image: clonediff/oncall-prober:latest
        envFrom:
        - configMapRef:
            name: oncall-prober-config
        imagePullPolicy: Never
        ports:
        - containerPort: 8000
